### ISSUE TITLE
Weird behavior with crs vectorfield

### ISSUE THREAD

**Issue by Hoxbro** [holoviz/hvplot#1137] opened 2023-09-14 17:16 UTC
I have absolutely no idea in which of our packages this problem lies.

I have a notebook with 3 cells (see below). If I run the cells in order, everything works, but after I have run the third cell, the second cell starts erroring out with the following: 

``` python-traceback
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[3], line 12
      2 val = np.arange(0, 100).reshape(10, 10)
      4 ds = xr.Dataset(
      5     data_vars={
      6         "mag": (("y", "x"), val),
   (...)
     10     attrs={"crs": crs},
     11 )
---> 12 ds.hvplot.vectorfield(x="x", y="y", angle="angle", mag="mag", geo=True)

File ~/Repos/holoviz/hvplot/hvplot/plotting/core.py:1687, in hvPlotTabular.vectorfield(self, x, y, angle, mag, **kwds)
   1628 def vectorfield(self, x=None, y=None, angle=None, mag=None, **kwds):
   1629     """
   1630     `vectorfield visualizes vectors given by the (`x , `y`) starting point, a magnitude (`mag`)
   1631     and an `angle` . A `vectorfield` plot is also known as a `quiver` plot.
   (...)
   1685     - Wiki: https://simple.wikipedia.org/wiki/Vector_field
   1686     """
-> 1687     return self(x, y, angle=angle, mag=mag, kind="vectorfield", **kwds)

File ~/Repos/holoviz/hvplot/hvplot/plotting/core.py:92, in hvPlotBase.__call__(self, x, y, kind, **kwds)
     89         plot = self._get_converter(x, y, kind, **kwds)(kind, x, y)
     90         return pn.panel(plot, **panel_dict)
---> 92 return self._get_converter(x, y, kind, **kwds)(kind, x, y)

File ~/Repos/holoviz/hvplot/hvplot/converter.py:1249, in HoloViewsConverter.__call__(self, kind, x, y)
   1247                 dataset = Dataset(data)
   1248             dataset = dataset.redim(**self._redim)
-> 1249         obj = method(x, y)
   1250         obj._dataset = dataset
   1252 if self.crs and self.project:
   1253     # Apply projection before rasterizing

File ~/Repos/holoviz/hvplot/hvplot/converter.py:2221, in HoloViewsConverter.vectorfield(self, x, y, angle, mag, data)
   2219 cur_opts, compat_opts = self._get_compat_opts('VectorField')
   2220 if self.geo: params['crs'] = self.crs
-> 2221 return (element(data, [x, y], z, **params).redim(**redim)
   2222         .apply(self._set_backends_opts, cur_opts=cur_opts, compat_opts=compat_opts))

File ~/Repos/holoviz/geoviews/geoviews/element/geo.py:113, in _Element.__init__(self, data, kdims, vdims, **kwargs)
    111 elif isinstance(data, _Element):
    112     kwargs['crs'] = data.crs
--> 113 super().__init__(data, kdims=kdims, vdims=vdims, **kwargs)

File ~/Repos/holoviz/holoviews/holoviews/element/selection.py:24, in SelectionIndexExpr.__init__(self, *args, **kwargs)
     23 def __init__(self, *args, **kwargs):
---> 24     super().__init__(*args, **kwargs)
     25     self._index_skip = False

File ~/Repos/holoviz/holoviews/holoviews/core/data/__init__.py:330, in Dataset.__init__(self, data, kdims, vdims, **kwargs)
    327 initialized = Interface.initialize(type(self), data, kdims, vdims,
    328                                    datatype=kwargs.get('datatype'))
    329 (data, self.interface, dims, extra_kws) = initialized
--> 330 super().__init__(data, **dict(kwargs, **dict(dims, **extra_kws)))
    331 self.interface.validate(self, validate_vdims)
    333 # Handle _pipeline property

File ~/Repos/holoviz/holoviews/holoviews/core/dimension.py:842, in Dimensioned.__init__(self, data, kdims, vdims, **params)
    839 if 'cdims' in params:
    840     params['cdims'] = {d if isinstance(d, Dimension) else Dimension(d): val
    841                        for d, val in params['cdims'].items()}
--> 842 super().__init__(data, **params)
    843 self.ndims = len(self.kdims)
    844 cdims = [(d.name, val) for d, val in self.cdims.items()]

File ~/Repos/holoviz/holoviews/holoviews/core/dimension.py:501, in LabelledData.__init__(self, data, id, plot_id, **params)
    498     util.group_sanitizer.add_aliases(**{alias:long_name})
    499     params['group'] = long_name
--> 501 super().__init__(**params)
    502 if not util.group_sanitizer.allowable(self.group):
    503     raise ValueError("Supplied group %r contains invalid characters." %
    504                      self.group)

File ~/Repos/holoviz/param/param/parameterized.py:3842, in Parameterized.__init__(self, **params)
   3840 if self.param.name.default == self.__class__.__name__:
   3841     self.param._generate_name()
-> 3842 self.param._setup_params(**params)
   3843 object_count += 1
   3845 self.param._update_deps(init=True)

File ~/Repos/holoviz/param/param/parameterized.py:1601, in as_uninitialized.<locals>.override_initialization(self_, *args, **kw)
   1599 original_initialized = parameterized_instance._param__private.initialized
   1600 parameterized_instance._param__private.initialized = False
-> 1601 fn(parameterized_instance, *args, **kw)
   1602 parameterized_instance._param__private.initialized = original_initialized

File ~/Repos/holoviz/param/param/parameterized.py:1881, in Parameters._setup_params(self_, **params)
   1876     raise TypeError(
   1877         f"{self.__class__.__name__}.__init__() got an unexpected "
   1878         f"keyword argument {name!r}"
   1879     )
   1880 # i.e. if not desc it's setting an attribute in __dict__, not a Parameter
-> 1881 setattr(self, name, val)

File ~/Repos/holoviz/param/param/parameterized.py:412, in instance_descriptor.<locals>._f(self, obj, val)
    410     instance_param.__set__(obj, val)
    411     return
--> 412 return f(self, obj, val)

File ~/Repos/holoviz/param/param/parameterized.py:1399, in Parameter.__set__(self, obj, val)
   1391     if self.set_hook is not _identity_hook:
   1392         # PARAM3_DEPRECATION
   1393         warnings.warn(
   1394             'Number.set_hook has been deprecated.',
   1395             category=_ParamDeprecationWarning,
   1396             stacklevel=5,
   1397         )
-> 1399 self._validate(val)
   1401 _old = NotImplemented
   1402 # obj can be None if __set__ is called for a Parameterized class

File ~/Repos/holoviz/param/param/__init__.py:1882, in ClassSelector._validate(self, val)
   1880 def _validate(self, val):
   1881     super()._validate(val)
-> 1882     self._validate_class_(val, self.class_, self.is_instance)

File ~/Repos/holoviz/param/param/__init__.py:1893, in ClassSelector._validate_class_(self, val, class_, is_instance)
   1891 if is_instance:
   1892     if not (isinstance(val, class_)):
-> 1893         raise ValueError(
   1894             f"{_validate_error_prefix(self)} value must be an instance of {class_name}, not {val!r}.")
   1895 else:
   1896     if not (issubclass(val, class_)):

ValueError: ClassSelector parameter '_Element.crs' value must be an instance of CRS, not None.
```

### Cells
``` python
import cartopy.crs as ccrs
import geoviews as gv
import hvplot.xarray  # noqa
import numpy as np
import xarray as xr
```

``` python
crs = ccrs.RotatedPole(pole_longitude=177.5, pole_latitude=37.5)
val = np.arange(0, 100).reshape(10, 10)

ds = xr.Dataset(
    data_vars={
        "mag": (("y", "x"), val),
        "angle": (("y", "x"), val),
    },
    coords={"x": np.arange(10), "y": np.arange(10)},
    attrs={"crs": crs},
)
ds.hvplot.vectorfield(x="x", y="y", angle="angle", mag="mag", geo=True)
```

``` python
dz = xr.tutorial.open_dataset("air_temperature")
dz.isel(time=0).hvplot("lon", "lat", coastline=True)
```

**Comment by ahuang11** [comment] 2023-09-14 17:50
I believe the issue stems from loading rio somewhere after calling the the second plot:
1.
<img width="838" alt="image" src="https://github.com/holoviz/hvplot/assets/15331990/ca4b18e7-d776-44d9-bbf9-a79758a07bec">

2.
<img width="521" alt="image" src="https://github.com/holoviz/hvplot/assets/15331990/c0e7a2ea-feff-49b9-9e3b-e7f49516ad45">

**Comment by jorisvandenbossche** [comment] 2023-09-19 15:40
We also ran into this issue when having a xarray.DataArray loaded with rioxarray that has "EPSG:3857" set as the `data.rio.crs`. Minimal reproducer:

```
In [11]: from hvplot.util import process_crs

In [12]: import pyproj

In [13]: process_crs(pyproj.CRS("EPSG:3857").to_wkt())
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
File ~/miniconda3/envs/test-/lib/python3.11/site-packages/hvplot/util.py:248, in process_crs(crs)
    247 try:
--> 248     crs = proj_to_cartopy(crs)
    249 except:

File ~/miniconda3/envs/test-/lib/python3.11/site-packages/hvplot/util.py:213, in proj_to_cartopy(proj)
    212 try:
--> 213     return cl(globe=globe, **kw_proj)
    214 except TypeError:

File ~/miniconda3/envs/test-/lib/python3.11/site-packages/cartopy/crs.py:1629, in Mercator.__init__(self, central_longitude, min_latitude, max_latitude, globe, latitude_true_scale, false_easting, false_northing, scale_factor)
   1628 if latitude_true_scale is not None:
-> 1629     raise ValueError('It does not make sense to provide both '
   1630                      '"scale_factor" and "latitude_true_scale". ')
   1631 else:

ValueError: It does not make sense to provide both "scale_factor" and "latitude_true_scale". 

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
Cell In[13], line 1
----> 1 process_crs(pyproj.CRS("EPSG:3857").to_wkt())

File ~/miniconda3/envs/test-/lib/python3.11/site-packages/hvplot/util.py:250, in process_crs(crs)
    248         crs = proj_to_cartopy(crs)
    249     except:
--> 250         raise ValueError("Could not parse EPSG code as CRS, must be of the format 'proj4: {proj4 string}.'")
    251 elif not isinstance(crs, ccrs.CRS):
    252     raise ValueError("Projection must be defined as a EPSG code, proj4 string, cartopy CRS or pyproj.Proj.")

ValueError: Could not parse EPSG code as CRS, must be of the format 'proj4: {proj4 string}.'
```

(I didn't check if this case is fixed with the open PR #1139)

**Comment by ahuang11** [comment] 2023-09-19 15:43
Seems to be still broken in #1139 

<img width="833" alt="image" src="https://github.com/holoviz/hvplot/assets/15331990/e7a1e156-4266-4043-9133-101a923585e9">

**Comment by ahuang11** [comment] 2023-09-19 15:51
Actually, I think this was fixed in:
https://github.com/holoviz/hvplot/pull/1092/files

**Closed** 2023-09-26 20:57 UTC
Labels: type: bug
