### ISSUE TITLE
Cannot have string groupby?

### ISSUE THREAD

**Issue by ahuang11** [holoviz/hvplot#437] opened 2020-04-06 20:01 UTC
```
import xarray as xr
import hvplot.xarray
ds = xr.tutorial.open_dataset('air_temperature')
ds['time'] = ds['time'].dt.strftime('%b %d %Y')
ds.hvplot('lon', 'lat', groupby='time')
```
panel==0.9.5
holoviews==1.13.2

```

~/anaconda3/envs/py3/lib/python3.7/site-packages/pandas/core/generic.py in __getattr__(self, name)
   5177             if self._info_axis._can_hold_identifiers_and_holds_name(name):
   5178                 return self[name]
-> 5179             return object.__getattribute__(self, name)
   5180 
   5181     def __setattr__(self, name, value):

AttributeError: 'DataFrame' object has no attribute 'data_vars'
```

**Comment by philippjfr** [comment] 2020-04-30 14:05
This is in fact not a bug, the problem is that by converting your coords to strings you have introduced duplicate coords. You should aggregate your data before passing it to hvPlot in this case:

```
ds.groupby('time').mean().hvplot('lon', 'lat', groupby='time')
```

**Comment by philippjfr** [comment] 2020-04-30 14:08
We should generate a better error message of course.

**Comment by jlstevens** [comment] 2020-08-03 16:02
@philippjfr I'll close this issue as resolved though maybe we want a new issue about improving the error message in this instance?

**Closed by jlstevens** 2020-08-03 16:02 UTC
