### ISSUE TITLE
Extension not loaded when importing `hvplot.pandas` after running `panel.extension()`

### ISSUE THREAD

**Issue by maximlt** [holoviz/hvplot#773] opened 2022-07-10 10:36 UTC
Recording a bug observed on the HoloViz tutorial after upgrading its pins to the latest hvplot/panel/holoviews/etc. Not sure it's a hvplot bug so this issue might have to be transferred to the right place after more investigation.

<img width="283" alt="image" src="https://user-images.githubusercontent.com/35924738/178141272-df6c531f-5e26-4376-a56e-ee5849d3c18c.png">

**Comment by philippjfr** [comment] 2022-07-10 21:21
Bug probably caused by the change to extension loading but the fix is indeed in hvPlot.

**Comment by philippjfr** [comment] 2022-07-10 21:30
Hmm, actually pretty confused by this. Don't see how this ever worked given the current logic.

**Closed** 2022-07-27 15:54 UTC
Labels: type: bug

**Comment by Cyb3r-Monk** [comment] 2022-09-26 07:34
@maximlt hvplot is still on 0.8.0 in `pkgs/main/osx-arm64`channel. Would it be possible to update it? I'd been having this issue and randomly found this bug and saw that osx-arm64 channel still had the buggy version.

**Comment by Hoxbro** [comment] 2022-09-26 07:48
It is not possible to update that channel by anyone on the holoviz team, but you can install it through the pyviz channel: `conda install -c pyviz hvplot=0.8.1`.
