### ISSUE TITLE
Transposing head(1) of an .interactive dataframe takes for ever

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/hvplot#671] opened 2021-11-01 05:45 UTC
hvplot: 0.7.3, holoviews: 1.14.6, pandas: 1.3.4

If I run the code below it runs for such a long time that I've not been able to see it finish. If I run the code without the `.T` it executes quickly.

https://user-images.githubusercontent.com/42288570/139626949-86a0a540-451d-4a55-bdca-139622dd3274.mp4

```python
import pandas as pd
import hvplot.pandas # Adds .hvplot and .interactive methods to Pandas dataframes

try:
    seattle_bikes = pd.read_csv("seattle_bikes.csv", parse_dates=["Date"]).set_index("Date")
except FileNotFoundError:
    seattle_bikes = pd.read_csv("https://data.seattle.gov/api/views/65db-xm6k/rows.csv?accessType=DOWNLOAD", parse_dates=["Date"]).set_index("Date")
    seattle_bikes.to_csv("seattle_bikes.csv")

def pipeline(seattle_bikes=seattle_bikes, frequency="D", window=50, center=True, win_type="gaussian", std=10):
    return (
        seattle_bikes.interactive()
        .resample(frequency)
        .sum()
        .rolling(window, center=center, win_type=win_type)
        .sum(std=std)
        .dropna()
    )
pipeline().head(1).T
```

**Comment by maximlt** [comment] 2022-10-14 18:11
I can't reproduce, this bug must have been fixed in the mean while 🎉

**Closed by maximlt** 2022-10-14 18:11 UTC
Labels: type: bug
