### ISSUE TITLE
Axes flipped when plotting an xarray.DataArray

### ISSUE THREAD

**Issue by maawoo** [holoviz/hvplot#668] opened 2021-10-21 13:49 UTC
#### ALL software version info
- Python 3.9.7 conda environment on CentOS 7
- hvplot=0.7.3
- holoviews=1.14.5
- datashader=0.13
- xarray=0.19

hvplot imported as `import hvplot.xarray`

#### Description of expected behavior and the observed behavior
Expected: 
Plot created from a 2-dimensional `xarray.DataArray` is by default plotted similarly to xarray's matplotlib wrapper, i.e. same orientation of axes.

Observed: 
x and y axes are flipped

#### Complete, minimal, self-contained example code that reproduces the issue
Can't provide a self-contained example but hopefully the following helps.

The `xarray.DataArray` with UTM x and y coordinates:
![grafik](https://user-images.githubusercontent.com/56583917/138289164-6dd82d11-3ac6-4bb8-80e2-e0adad9fa1d8.png)

Plot using xarray's matplotlib wrapper showing the correct orientation:
```python
ds.plot(cmap='viridis', figsize=(12, 10))
``` 
![grafik](https://user-images.githubusercontent.com/56583917/138104177-fdf1eeff-d3c7-4cc6-9389-707fd9426c4e.png)

Plots using hvplot (same problem with `.hvplot` and `.hvplot.image`) with some flippin' going on:
```python
ds.hvplot(cmap='viridis', height=600, width=800) 
ds.hvplot.image(cmap='viridis', height=600, width=800)
```
![grafik](https://user-images.githubusercontent.com/56583917/138104441-0b5a7050-2bc8-4930-a571-21d658fe7a9d.png)

**Comment by philippjfr** [comment] 2021-10-21 15:20
Thanks for the issue!

>Shouldn't x='x', y='y' be the default, however?

I'd prefer not to add any special case logic looking for specific coordinate names so definitely -1 on that. However since xarray somehow figures out the appropriate axis ordering in this case we will have to take another look at how they do it compared to how we do it.

**Comment by maximlt** [comment] 2022-03-25 19:16
xarray reverses the DataArray dims, it considers the x-axis as dims[1] and and the y-axis as dims[0].
![image](https://user-images.githubusercontent.com/35924738/160186275-1378b8c3-f1be-4780-9b16-81cc46aac456.png)

This is defined here:
https://github.com/pydata/xarray/blob/f8bae5974ee2c3f67346298da12621af4cae8cf8/xarray/plot/utils.py#L376

In the example provided by the OP the DataArray dimensions are `('y', 'x')` so when reversed they are "correctly" displayed. I don't know if this inversion done by xarray lies on some sort of convention but without any more context (no attributes parsing or anything else), it seems to me it's a little too arbitrary, and anyway easily handled at the hvplot level with `x='x', y='y'`. I'm going to close this issue then, if this happens to rely on a convention I was not aware please let me know and I'll happily implement xarray's behavior.

**Closed by maximlt** 2022-03-25 19:16 UTC
Labels: type: bug

**Comment by maximlt** [comment] 2022-03-28 10:48
@philippjfr should we reproduce what xarray does, as asked in this issue?
