### ISSUE TITLE
hvplot with option geo=True leads to ValueError: cannot convert float NaN to integer

### ISSUE THREAD

**Issue by anderl80** [holoviz/hvplot#431] opened 2020-03-30 10:18 UTC
Not specifying width and height or aspect leads to an error.

#### ALL software version info
bokeh: 2.0.0
holovies: 1.13.1
geoviews: 1.8.1
hvplot: 0.5.2

#### Complete, minimal, self-contained example code that reproduces the issue

```
pd.DataFrame([(11.621, 48.135)], columns=["lon", "lat"]).hvplot.points(geo=True)
```

#### Stack traceback and/or browser JavaScript console output

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~/.conda/envs/efa_related/lib/python3.6/site-packages/IPython/core/formatters.py in __call__(self, obj, include, exclude)
    968 
    969             if method is not None:
--> 970                 return method(include=include, exclude=exclude)
    971             return None
    972         else:

~/.conda/envs/efa_related/lib/python3.6/site-packages/holoviews/core/dimension.py in _repr_mimebundle_(self, include, exclude)
   1302         combined and returned.
   1303         """
-> 1304         return Store.render(self)
   1305 
   1306 

~/.conda/envs/efa_related/lib/python3.6/site-packages/holoviews/core/options.py in render(cls, obj)
   1393         data, metadata = {}, {}
   1394         for hook in hooks:
-> 1395             ret = hook(obj)
   1396             if ret is None:
   1397                 continue

~/.conda/envs/efa_related/lib/python3.6/site-packages/holoviews/ipython/display_hooks.py in pprint_display(obj)
    280     if not ip.display_formatter.formatters['text/plain'].pprint:
    281         return None
--> 282     return display(obj, raw_output=True)
    283 
    284 

~/.conda/envs/efa_related/lib/python3.6/site-packages/holoviews/ipython/display_hooks.py in display(obj, raw_output, **kwargs)
    250     elif isinstance(obj, (CompositeOverlay, ViewableElement)):
    251         with option_state(obj):
--> 252             output = element_display(obj)
    253     elif isinstance(obj, (Layout, NdLayout, AdjointLayout)):
    254         with option_state(obj):

~/.conda/envs/efa_related/lib/python3.6/site-packages/holoviews/ipython/display_hooks.py in wrapped(element)
    144         try:
    145             max_frames = OutputSettings.options['max_frames']
--> 146             mimebundle = fn(element, max_frames=max_frames)
    147             if mimebundle is None:
    148                 return {}, {}

~/.conda/envs/efa_related/lib/python3.6/site-packages/holoviews/ipython/display_hooks.py in element_display(element, max_frames)
    190         return None
    191 
--> 192     return render(element)
    193 
    194 

~/.conda/envs/efa_related/lib/python3.6/site-packages/holoviews/ipython/display_hooks.py in render(obj, **kwargs)
     66         renderer = renderer.instance(fig='png')
     67 
---> 68     return renderer.components(obj, **kwargs)
     69 
     70 

~/.conda/envs/efa_related/lib/python3.6/site-packages/holoviews/plotting/renderer.py in components(self, obj, fmt, comm, **kwargs)
    363             doc = Document()
    364             with config.set(embed=embed):
--> 365                 model = plot.layout._render_model(doc, comm)
    366             return render_model(model, comm) if embed else render_mimebundle(model, doc, comm)
    367         else:

~/.conda/envs/efa_related/lib/python3.6/site-packages/panel/viewable.py in _render_model(self, doc, comm)
    363         if comm is None:
    364             comm = state._comm_manager.get_server_comm()
--> 365         model = self.get_root(doc, comm)
    366 
    367         if config.embed:

~/.conda/envs/efa_related/lib/python3.6/site-packages/panel/viewable.py in get_root(self, doc, comm)
    534         """
    535         doc = doc or _curdoc()
--> 536         root = self._get_model(doc, comm=comm)
    537         self._preprocess(root)
    538         ref = root.ref['id']

~/.conda/envs/efa_related/lib/python3.6/site-packages/panel/layout.py in _get_model(self, doc, root, parent, comm)
    134         if root is None:
    135             root = model
--> 136         objects = self._get_objects(model, [], doc, root, comm)
    137         props = dict(self._init_properties(), objects=objects)
    138         model.update(**self._process_param_change(props))

~/.conda/envs/efa_related/lib/python3.6/site-packages/panel/layout.py in _get_objects(self, model, old_objects, doc, root, comm)
    124             else:
    125                 try:
--> 126                     child = pane._get_model(doc, root, model, comm)
    127                 except RerenderError:
    128                     return self._get_objects(model, current_objects[:i], doc, root, comm)

~/.conda/envs/efa_related/lib/python3.6/site-packages/panel/pane/holoviews.py in _get_model(self, doc, root, parent, comm)
    225             plot = self.object
    226         else:
--> 227             plot = self._render(doc, comm, root)
    228 
    229         plot.pane = self

~/.conda/envs/efa_related/lib/python3.6/site-packages/panel/pane/holoviews.py in _render(self, doc, comm, root)
    284             kwargs = {}
    285 
--> 286         return renderer.get_plot(self.object, **kwargs)
    287 
    288     def _cleanup(self, root):

~/.conda/envs/efa_related/lib/python3.6/site-packages/holoviews/plotting/bokeh/renderer.py in get_plot(self_or_cls, obj, doc, renderer, **kwargs)
     71         combining the bokeh model with another plot.
     72         """
---> 73         plot = super(BokehRenderer, self_or_cls).get_plot(obj, doc, renderer, **kwargs)
     74         if plot.document is None:
     75             plot.document = Document() if self_or_cls.notebook_context else curdoc()

~/.conda/envs/efa_related/lib/python3.6/site-packages/holoviews/plotting/renderer.py in get_plot(self_or_cls, obj, doc, renderer, comm, **kwargs)
    221             init_key = tuple(v if d is None else d for v, d in
    222                              zip(plot.keys[0], defaults))
--> 223             plot.update(init_key)
    224         else:
    225             plot = obj

~/.conda/envs/efa_related/lib/python3.6/site-packages/holoviews/plotting/plot.py in update(self, key)
    876     def update(self, key):
    877         if len(self) == 1 and ((key == 0) or (key == self.keys[0])) and not self.drawn:
--> 878             return self.initialize_plot()
    879         item = self.__getitem__(key)
    880         self.traverse(lambda x: setattr(x, '_updated', True))

~/.conda/envs/efa_related/lib/python3.6/site-packages/geoviews/plotting/bokeh/plot.py in initialize_plot(self, ranges, plot, plots, source)
    110     def initialize_plot(self, ranges=None, plot=None, plots=None, source=None):
    111         opts = {} if isinstance(self, HvOverlayPlot) else {'source': source}
--> 112         fig = super(GeoPlot, self).initialize_plot(ranges, plot, plots, **opts)
    113         if self.geographic and self.show_bounds and not self.overlaid:
    114             from . import GeoShapePlot

~/.conda/envs/efa_related/lib/python3.6/site-packages/holoviews/plotting/bokeh/element.py in initialize_plot(self, ranges, plot, plots, source)
   1318         if not self.overlaid:
   1319             self._update_plot(key, plot, style_element)
-> 1320             self._update_ranges(style_element, ranges)
   1321 
   1322         for cb in self.callbacks:

~/.conda/envs/efa_related/lib/python3.6/site-packages/geoviews/plotting/bokeh/plot.py in _update_ranges(self, element, ranges)
     89 
     90     def _update_ranges(self, element, ranges):
---> 91         super(GeoPlot, self)._update_ranges(element, ranges)
     92         if not self.geographic:
     93             return

~/.conda/envs/efa_related/lib/python3.6/site-packages/holoviews/plotting/bokeh/element.py in _update_ranges(self, element, ranges)
    834                 if fixed_height:
    835                     plot.frame_height = height
--> 836                     plot.frame_width = int(height/aspect)
    837                     plot.plot_width, plot.plot_height = None, None
    838                 elif fixed_width:

ValueError: cannot convert float NaN to integer
```

**Comment by ahuang11** [comment] 2020-04-01 00:00
Seems to be fixed in later versions; installed bokeh-2.0.1 geoviews-1.8.1 holoviews-1.13.1
![image](https://user-images.githubusercontent.com/15331990/78085862-d1706180-7381-11ea-9278-8763133d56e9.png)

**Comment by anderl80** [comment] 2020-04-02 07:19
Thanks for testing @ahuang11 , I will try to upgrade to the versions you used.

**Comment by anderl80** [comment] 2020-04-02 07:59
![grafik](https://user-images.githubusercontent.com/23196828/78224289-9462b700-74c8-11ea-8289-1e27331dd48e.png)
It seemes not fixed for me.

**Comment by anderl80** [comment] 2020-04-02 08:05
Also, when specifying width and height explictly, bounding box is not set correctly.
![grafik](https://user-images.githubusercontent.com/23196828/78224788-6e89e200-74c9-11ea-9736-c3b719cc5197.png)

**Comment by philippjfr** [comment] 2020-04-23 22:14
Can't reproduce any of the problems reported here.

**Comment by anderl80** [comment] 2020-04-29 18:43
Did you install using conda and which channel priority?

**Comment by ceball** [comment] 2020-08-24 15:43
Also can't reproduce with bokeh 2.1.1, hvplot 0.6.0, geoviews 1.8.1, holoviews 1.13.3 (all from conda-forge). I do see the hover tool issue covered by #433

**Closed by ceball** 2020-08-24 15:43 UTC
