### ISSUE TITLE
Deprecation Warning

### ISSUE THREAD

**Issue by michaelaye** [holoviz/hvplot#441] opened 2020-04-09 21:39 UTC
#### ALL software version info
(this library, plus any other relevant software, e.g. bokeh, python, notebook, OS, browser, etc)
```bash
# packages in environment at /Users/klay6683/miniconda3/envs/py37:
#
# Name                    Version                   Build  Channel
holoviews                 1.13.2             pyh9f0ad1d_0    conda-forge
# packages in environment at /Users/klay6683/miniconda3/envs/py37:
#
# Name                    Version                   Build  Channel
hvplot                    0.5.2                      py_0    conda-forge
# packages in environment at /Users/klay6683/miniconda3/envs/py37:
#
# Name                    Version                   Build  Channel
bokeh                     2.0.1            py37hc8dfbb8_0    conda-forge
```

#### Description of expected behavior and the observed behavior
I'm getting a deprecation warning using a default pd.Series.hvplot() involving holoviews.CurvePlot regarding the use of the `title` keyword. (The warning only occurs when I use `title`).
As I have no means on controlling how `hvplot` is using the `holoviews` items, I expect no deprecation on the user-side.

#### Complete, minimal, self-contained example code that reproduces the issue

```
import hvplot.pandas
pd.Series(np.arange(10)).hvplot(title='Test')
```

#### Stack traceback and/or browser JavaScript console output
```python
WARNING:param.CurvePlot01535: title_format is deprecated. Please use title instead
WARNING:param.CurvePlot01535: title_format is deprecated. Please use title instead
```
(Interestingly, the warning appears twice.)

#### Screenshot
<img width="792" alt="Screen Shot 2020-04-09 at 15 39 27" src="https://user-images.githubusercontent.com/69774/78943087-4f1a2880-7a78-11ea-9870-052db1176cfe.png">

**Comment by philippjfr** [comment] 2020-04-09 22:04
Thanks, duplicate of https://github.com/holoviz/hvplot/issues/426 hopefully I'll find some time this weekend to update and releasee hvPlot.

**Closed by philippjfr** 2020-04-09 22:04 UTC

**Comment by michaelaye** [comment] 2020-04-09 22:06
aw, man, i searched for CurvePlot only, so i didn't see that, sorry.

**Comment by philippjfr** [comment] 2020-04-09 22:08
Always better to report it. Thanks for doing so consistently, it's really helpful generally.
