### ISSUE TITLE
hvplot.image() zoom causes axes limits to bounce around

### ISSUE THREAD

**Issue by scottyhq** [holoviz/hvplot#462] opened 2020-05-08 00:33 UTC
Thanks for contacting us! Please read and follow these instructions carefully, then delete this introductory text to keep your issue easy to read. Note that the issue tracker is NOT the place for usage questions and technical assistance; post those at [Discourse](https://discourse.holoviz.org) instead. Issues without the required information below may be closed immediately.

#### ALL software version info
hvplot 0.5.2
bokeh 2.0.1

#### Description of expected behavior and the observed behavior
Plotting image results in axes and colorbar limits jumping around. A zoom box draw partially outside valid pixels of image causes further jumping around of axes limits.
 
#### Complete, minimal, self-contained example code that reproduces the issue
https://gist.github.com/scottyhq/0e245fcd62d8a46b82a4186fcd8945e6#file-hvplot-zoom-ipynb
```
# Lots of window and colorbar rescaling happening when first plot, and upon zooming
band1.hvplot.image(x='x',y='y',
                   crs='epsg:32645', 
                   tiles='OSM', 
                   rasterize=True,
                   width=700, height=500, 
                   cmap='plasma', 
                   logz=True,
                   alpha=0.7)
```

#### Stack traceback and/or browser JavaScript console output
 No error or traceback, but the behavior is buggy. See gif:

#### Screenshots or screencasts of the bug in action
![hvplotzoom](https://user-images.githubusercontent.com/3924836/81357487-a1a33080-9088-11ea-8e5b-8955c7dad0d0.gif)

**Comment by rsignell-usgs** [comment] 2020-05-08 09:48
We see this too.  https://github.com/intake/xrviz/issues/70#issuecomment-618535505

**Comment by philippjfr** [comment] 2020-05-17 20:57
Can't seem to reproduce anymore with latest versions of everything. Will make dev versions of everything available for testing.

**Comment by scottyhq** [comment] 2020-06-05 01:09
@philippjfr - This still seems to be an issue with the latest hvplot release (0.6). I updated the binder link in the first comment with new versions, so that you can reproduce the issue. The bug seems to be limited to when `crs` is set as an argument.

**Comment by philippjfr** [comment] 2020-06-05 01:11
I think this won't be fixed properly until I release HoloViews 1.13.3. Hopefully this weekend.

**Comment by scottyhq** [comment] 2020-06-12 22:31
Related issue: https://github.com/holoviz/geoviews/issues/418

**Comment by philippjfr** [comment] 2020-06-13 13:05
I can still reproduce this but tackling this now before I release 1.13.3. Note that a workaround for now is to set a `frame_width` and `frame_height`. The problem is that the initial aspect calculations are off because the regular width/height include the axes and colorbars, which means that once it knows the size of the canvas it makes a number of adjustments and gets into weird loops because the width of tick labels changes which again causes the canvas area to change in size causing another change in the aspect and so on.

**Comment by rsignell-usgs** [comment] 2020-07-22 14:24
@philippjfr, I'm still getting this issue with holoviews 1.13.3 in certain cases (although I can fix it by setting `frame_width` and `frame_height` as you suggest).  

[This video ](https://www.screencast.com/t/1UhIsFqqqsC) demonstrates the problem. 

The code to reproduce the video is:
```python
import xarray as xr
import hvplot.xarray

url = ('http://geoport.whoi.edu/thredds/dodsC/vortexfs1/usgs/users'
      '/scook/proj/DE_Bay/run07/subtidal/de_bay_run07_subtidal.ncml')

ds = xr.open_dataset(url)
ds.salt.sel(ocean_time='2017-08-05')[-1,:,:].hvplot.quadmesh(x='lon_rho',y='lat_rho', 
            geo=True, tiles='OSM', rasterize=True, cmap='rainbow')
```
And then change the value using the selection slider.

**Comment by rsignell-usgs** [comment] 2020-07-22 14:36
Ugh.  I'm getting it also even if I specify the `frame_width` and `frame_height`:

https://www.screencast.com/t/qyLnryCbbv

**Comment by philippjfr** [comment] 2020-07-22 14:37
Strange, I can definitely reproduce.

**Comment by philippjfr** [comment] 2020-08-24 15:01
@rsignell-usgs The dataset doesn't seem to be available anymore: http://geoport.whoi.edu/thredds/dodsC/vortexfs1/usgs/users/scook/proj/DE_Bay/run07/subtidal/de_bay_run07_subtidal.ncml

Is there anywhere I can access it?

**Comment by rsignell-usgs** [comment] 2020-08-24 15:22
@philippjfr , 
The link you provided is the OPeNDAP Data URL -- you need to add a `.html` to the end of that to browse the dataset metadata in the browser, so:
http://geoport.whoi.edu/thredds/dodsC/vortexfs1/usgs/users/scook/proj/DE_Bay/run07/subtidal/de_bay_run07_subtidal.ncml.html

I just tried the python code above though, and it worked.

**Comment by philippjfr** [comment] 2020-08-26 19:23
I think I've finally got a real fix here, my previous approach was very obviously wrong after looking at it again. Will try to get 1.13.4 out asap.

**Closed** 2020-08-26 22:17 UTC
Labels: type: bug

**Comment by JessicaS11** [comment] 2020-09-15 16:09
Any update on when we can expect 1.13.4? I recently started using Holoviews and have been liking it so far, but have been having to force restart my kernel frequently due to this issue. I was excited to learn that it was already a known bug that has a fix coming in the next release!

**Comment by philippjfr** [comment] 2020-09-15 16:44
I'm currently trying to fix an issue building the documentation for HoloViews. Otherwise nothing is holding up the release now so I'm hoping today or tomorrow is the date.
