### ISSUE TITLE
When using argument groupby and doing a dropdown selection, the wrong data points are displayed

### ISSUE THREAD

**Issue by SandervandenOord** [holoviz/hvplot#499] opened 2020-08-13 14:47 UTC
holoviews: '1.13.4a1'
hvplot: '0.6.0rc4.post5+g9213abf'

When I use the groupby argument in hvplot, this gives me a dropdown to make selections. 
However this is not working properly. 
The first default plot shown seems to be correct, but once you use the dropdown, it starts mixing up data. 
Sometimes data is shown from the first (default) selection, although you selected a different value. Sometimes no datapoints are shown. Sometimes datapoints are shown, but when you hover over a datapoint, you only see question marks.

I think it seems that the default data selected is also used for the plots after you change the selection.

The groupby argument is very powerful (creating a dropdown selection), especially in comparison to other plotting packages, but currently it's unusable, because I can't trust what the plot shows me. I use it to rapidly explore my dataset.

Example code:
``` python
import numpy as np
import pandas as pd
import hvplot.pandas

np.random.seed(42)

data2 = {
    'company': np.random.choice(['AAA', 'BBB', 'CCC', 'DDD'], size=20),
    'sales': np.random.uniform(low=1.0, high=1000, size=20),
    'date': pd.date_range(start='2020-01-01', periods=20, freq='D')
}
test_df2 = pd.DataFrame(data2)
test_df2.hvplot.scatter(x='date', y='sales', groupby='company', hover_cols='all', padding=1.0)
```
![image](https://user-images.githubusercontent.com/7305600/90148395-934d6a80-dd83-11ea-97dd-a820a27314d2.png)

![image](https://user-images.githubusercontent.com/7305600/90148823-15d62a00-dd84-11ea-8e8c-e595b2a3056b.png)

**Comment by philippjfr** [comment] 2020-08-13 14:50
So strangely I can't reproduce. @holoviz/triaging-team Can anyone else reproduce this?

**Comment by SandervandenOord** [comment] 2020-08-13 15:05
Ok, @philippjfr: now these first examples do work correctly on my local machine, but not correctly on my VM in google cloud, although they both were new virtual environment installed and created today, which I still find worrying.
Can you please still try this code, which is 'groupby' and 'by' combined. Please change selections a couple of times and compare data shown with the actual data. It seems the legend is not displaying the correct categories:
```python
import numpy as np
import pandas as pd
import hvplot.pandas

np.random.seed(42)

data = {
    'company': np.random.choice(['AAA', 'BBB', 'CCC', 'DDD'], size=20),
    'product': np.random.choice(['A1', 'B2', 'C3', 'D4'], size=20),
    'sales': np.random.uniform(low=1.0, high=1000, size=20),
    'date': pd.date_range(start='2020-01-01', periods=20, freq='D')
}

test_df = pd.DataFrame(data)

test_df.hvplot.scatter(x='date', y='sales', groupby='company', by='product', hover_cols='all')
```
![image](https://user-images.githubusercontent.com/7305600/90151587-276d0100-dd87-11ea-8e3b-21d434537146.png)

**Comment by philippjfr** [comment] 2020-08-14 12:31
I can definitely reproduce those issues.

**Comment by SandervandenOord** [comment] 2020-08-14 12:53
The Google Cloud platfrom currently comes with jupyterlab 1.2.16 installed (and this cannot be easily upgraded to 2.x) Could this also be the reason for the issues with the first?
Problems I run into is that I have the feeling I need a very specific setup to get everything precisely working as it should with precisely the right packages and versions and way of installing. Sometimes this can even be the difference between a conda install or a pip install in my conda environment. 
Thing is: data science is shifting more to cloud: spinning up a cloud notebook (GC / AWS / Azure) on a good VM with some stuff pre-installed. This makes it very difficult to get the right setup for a working hvplot / holoviews environment.

**Comment by mc51** [comment] 2020-09-02 10:16
This seems to be related to [my issue ](https://github.com/holoviz/hvplot/issues/506).
For me, the result of your code is the same as in my isssue:
It works in Jupyterlab but does not work in the browser.

**Comment by SandervandenOord** [comment] 2020-10-19 18:37
I'm now using a workaround by setting `dynamic=False` to create a HoloMap instead of a DynamicMap

**Comment by philippjfr** [comment] 2021-05-21 23:55
Fixed with latest HoloViews.

**Closed by philippjfr** 2021-05-21 23:55 UTC
