### ISSUE TITLE
Vectorfield not overlaid properly on Tiles

### ISSUE THREAD

**Issue by ahuang11** [holoviz/hvplot#1093] opened 2023-06-21 19:49 UTC
https://hvplot.holoviz.org/reference/xarray/vectorfield.html#geographic-data
<img width="956" alt="image" src="https://github.com/holoviz/hvplot/assets/15331990/276b06c0-bb99-452d-94c9-e5cb01caae34">

**Comment by jbednar** [comment] 2023-06-21 19:54
Can you explain what the issue is here? Does CartoLight display properly on its own?

**Comment by ahuang11** [comment] 2023-06-21 19:57
Sorry, should have clarified:
<img width="627" alt="image" src="https://github.com/holoviz/hvplot/assets/15331990/6e4ab658-b4ae-4e61-a0b6-f1bfa4cc2345">

If you zoom far enough out, you should see:
<img width="585" alt="image" src="https://github.com/holoviz/hvplot/assets/15331990/d51571f7-9ed5-4f7e-aa3d-d2297896fe38">

I don't think it should be stationed there because the lat/lon is -30 to 30
<img width="810" alt="image" src="https://github.com/holoviz/hvplot/assets/15331990/c41564eb-87f4-4319-b9c1-3c0453562f76">

**Comment by ahuang11** [comment] 2023-06-21 20:05
```python
import cartopy.crs as ccrs

ds.hvplot.vectorfield(x='x', y='y', angle='angle', mag='mag',
                      hover=False, geo=True, crs=ccrs.PlateCarree()).opts(projection=ccrs.GOOGLE_MERCATOR, magnitude='mag') * gv.tile_sources.CartoLight
```

This is what I expected to see:
<img width="1057" alt="image" src="https://github.com/holoviz/hvplot/assets/15331990/722c8190-3521-490a-bb3d-2af4f698efe3">

**Comment by jbednar** [comment] 2023-06-21 20:10
Ok, so since this example presumably worked when the notebook was written, somehow we are erroneously no longer projecting the data when `geo=True`. Yikes!

**Comment by Hoxbro** [comment] 2023-06-21 20:43
I think this is related to #1090, which was caused by #1053. If I turn my git back before that PR was merged, this is the output:

![image](https://github.com/holoviz/hvplot/assets/19758978/46ae3ae4-137c-48c5-ae62-4ffe4371790a)

**Comment by ahuang11** [comment] 2023-06-21 20:44
I suspect that output is also incorrect because the y is from -20 to 20

**Comment by Hoxbro** [comment] 2023-06-21 21:18
This is not my expertise, but could the linear coordinates be on the CRS, which does not align with the tile?

Putting the linear x and y values on the CRS
![image](https://github.com/holoviz/hvplot/assets/19758978/d1e7f6c5-5ad3-444e-8943-26b191b35f84)

Like this:
![image](https://github.com/holoviz/hvplot/assets/19758978/8e02fdd1-6649-4bb0-bc9e-ddb7c7ae0fa5)

And then convert it to the tiles projection. This will mean that the north pole will be more spread out than the equator, which is what is seen in my previous comment.

**Comment by ahuang11** [comment] 2023-06-22 01:24
I am not sure I follow, but probably because I didn't elaborate what I meant by incorrect.

The `y` ranges from -23N (below the equator) to 24.6N
<img width="658" alt="image" src="https://github.com/holoviz/hvplot/assets/15331990/5a8a6549-5983-48ce-863f-de95385b4f3d">

This ranges from 20-70N
<img width="753" alt="Screenshot 2023-06-21 at 9 22 40 PM" src="https://github.com/holoviz/hvplot/assets/15331990/7002a367-1ea0-4408-862a-8e66e077a91b">

Therefore I believe this is the correct one
![image](https://github.com/holoviz/hvplot/assets/15331990/6ba6ff3f-c6e2-4543-827f-35986b96c073)

**Comment by ahuang11** [comment] 2023-06-22 01:30
Okay I just realized the data's crs was RotatedPole; what you have is correct.

```python
ds.hvplot.vectorfield(x='x', y='y', angle='angle', mag='mag', crs=crs,
                      hover=False).opts(magnitude='mag', projection=ccrs.GOOGLE_MERCATOR) * gv.tile_sources.CartoLight
```

**Closed** 2023-10-03 06:19 UTC
Labels: type: bug
