### ISSUE TITLE
scatter_matrix y-axis label replaces first column name with 'Frequency'

### ISSUE THREAD

**Issue by jordansamuels** [holoviz/hvplot#388] opened 2019-12-01 18:29 UTC
#### ALL software version info (hvPlot, holoviews, bokeh, python, notebook, OS, browser, any other relevant packages)
* hvPlot: 0.5.2.post13+gc313d35-dirty (using latest master as of today)
* bokeh 1.4.0
* python: Python 3.6.9 :: Anaconda, Inc.
* notebook: 6.0.2
* OS: OSX
* browser: chrome 

#### Description of expected behavior and the observed behavior
* Expected behavior: y-axis label should have all column names, e.g. name `petal_length` in the example below.
* Observed behavior: y-axis label has `Frequency` for the first column name label (not `petal_length`).  All other column names are reflected properly in the y-axis label.
* All x-axis labels are correct.
#### Complete, minimal, self-contained example code that reproduces the issue
This example is from [the Statistical_Plots example notebook/doc](https://github.com/holoviz/hvplot/blob/master/examples/user_guide/Statistical_Plots.ipynb?short_path=cad903b#L39)
```
import pandas as pd
import hvplot.pandas  # noqa
from bokeh.sampledata import iris, stocks 
iris = iris.flowers
hvplot.scatter_matrix(iris, c="species")
```

#### Screenshots or screencasts of the bug in action
![image](https://user-images.githubusercontent.com/610909/69918324-17e69b80-1436-11ea-8bfb-ca8500a441aa.png)

**Comment by philippjfr** [comment] 2019-12-03 00:23
Duplicate of https://github.com/holoviz/holoviews/issues/1507

**Comment by philippjfr** [comment] 2019-12-03 00:23
Thanks for reporting, this is originally a HoloViews issue.

**Closed by philippjfr** 2019-12-03 00:23 UTC
Labels: TRIAGE

**Comment by jordansamuels** [comment] 2019-12-04 14:15
@philippjfr yes, sorry for not checking holoviews first, I should have realized it's a hv element issue.
