### ISSUE TITLE
TypeError on page https://hvplot.holoviz.org/user_guide/Plotting.html

### ISSUE THREAD

**Issue by SandervandenOord** [holoviz/hvplot#538] opened 2020-12-18 20:49 UTC
There's currently an error displayed for this code block on page https://hvplot.holoviz.org/user_guide/Plotting.html:

``` python
flight_subset = flights[flights.carrier.isin([b'AA', b'US', b'OH'])]
flight_subset.hvplot.hist('depdelay', by='carrier', bins=20, bin_range=(-20, 100), width=300, subplots=True)
```

![Screenshot 2020-12-18 at 21 47 17](https://user-images.githubusercontent.com/7305600/102660028-ac738700-417a-11eb-9cf2-c287ce963e65.png)

> TypeError: Object of type 'Array' is not JSON serializable
> :NdLayout   [carrier]
>    :Histogram   [depdelay]   (depdelay_count)

**Comment by jlstevens** [comment] 2021-01-25 17:04
Thanks for reporting this error!

Definitely should be working so I'll file it as a bug and assign it to the next milestone.

**Comment by brl0** [comment] 2021-04-07 18:51
After accidentally creating a duplicate of this issue in #583, I think I found the problem.
The issue seems to be the bytes objects in the carrier list, the example works with regular strings, so just change this line:

```python
flight_subset = flights[flights.carrier.isin(['AA', 'US', 'OH'])]
```

**Closed** 2021-04-07 19:34 UTC
Labels: type: docs
