### ISSUE TITLE
violin plot not working with latest hvplot

### ISSUE THREAD

**Issue by aulemahal** [holoviz/hvplot#498] opened 2020-07-30 16:08 UTC
#### ALL software version inf
Bug seen with hvplot 0.6.0 and
- bokeh 2.0.1 and 2.1.1
- python 3.8 (.3 and .5)
- xarray 0.15.2 and 0.16
- holoviews 1.13.3
In a jupyter notebook running in Firefox 78.0.2, on linux (Arch Linux)
Also seen in Chromium 84.0 on the same machine.

Bug not seen (violin plot showing correctly) on hvplot 0.5.2, bokeh 2.0.1, python 3.8, holoviews 1.13.3 and xarray 0.15.0 (same browser and machine)

#### Description of expected behavior and the observed behavior
Plotting xarray data to a violin plot with hvplot results in an empty bokeh figure. All axes are correct, with the expected data limits, but the plot is blank.

#### Complete, minimal, self-contained example code that reproduces the issue
I simply executed the ("gridded datasets" notebook)[http://holoviews.org/user_guide/Gridded_Datasets.html]
```
# code goes here between backticks
import xarray as xr
import hvplot.xarray  # noqa

air_ds = xr.tutorial.open_dataset('air_temperature').load()
air = air_ds.air
air.hvplot.violin('air', by='lat', color='lat', cmap='Category20')
```

#### Stack traceback and/or browser JavaScript console output
No problematic tracebacks.. The browser console says:
```
Bokeh: BokehJS plotting callback run at Date Thu Jul 30 2020 12:01:30 GMT-0400 (heure d’été de l’Est) main.min.js:1167:15
[bokeh] setting log level to: 'info' main.min.js:354:1390
Bokeh: all callbacks have finished main.min.js:28:13
[bokeh] document idle at 87 ms main.min.js:276:1256
```

#### Screenshots or screencasts of the bug in action
![Capture d’écran de 2020-07-30 12-03-24](https://user-images.githubusercontent.com/20629530/88946089-d1636e00-d25c-11ea-926b-c10adc894e70.png)

**Comment by tonyfast** [comment] 2020-08-03 15:20
I can reproduce this 🐛.

**Comment by philippjfr** [comment] 2020-11-14 23:33
This has since been fixed in HoloViews.

**Closed by philippjfr** 2020-11-14 23:33 UTC
Labels: type: bug, upstream
