### ISSUE TITLE
pandas dtype Int64 not recognised as numeric in plot.box()

### ISSUE THREAD

**Issue by CodeCox** [holoviz/hvplot#552] opened 2021-01-26 09:00 UTC
## Description
plot.box() fails with `No numeric types to aggregate` when using the **_pandas_** dtype `Int64` in a dataframe. However, the **_standard_** dtype `int64` works.  

## Example code
```
data = np.random.randint(1, 9, (10, 5))
df = pd.DataFrame(data, columns=['A', 'B', 'C', 'D', 'E'], dtype='Int64')
df.plot.box()
```

## Traceback and Output
_**Cell output**_
```
DataError [Call holoviews.ipython.show_traceback() for details]
No numeric types to aggregate
```

<details><summary>Subsequent Traceback</summary><p>

```
Traceback (most recent call last):

  File "C:\Users\mydev\Miniconda3\envs\jlab3\lib\site-packages\holoviews\plotting\bokeh\element.py", line 1583, in _init_glyphs
    group_style = self._apply_transforms(element, ds_data, ranges, group_style, style_group)

  File "C:\Users\mydev\Miniconda3\envs\jlab3\lib\site-packages\holoviews\plotting\bokeh\stats.py", line 113, in _apply_transforms
    element = element.aggregate(function=np.mean)

  File "C:\Users\mydev\Miniconda3\envs\jlab3\lib\site-packages\holoviews\core\data\__init__.py", line 201, in pipelined_fn
    result = method_fn(*args, **kwargs)

  File "C:\Users\mydev\Miniconda3\envs\jlab3\lib\site-packages\holoviews\core\data\__init__.py", line 917, in aggregate
    aggregated, dropped = self.interface.aggregate(self, kdims, function, **kwargs)

  File "C:\Users\mydev\Miniconda3\envs\jlab3\lib\site-packages\holoviews\core\data\pandas.py", line 244, in aggregate
    df = grouped.aggregate(fn, **kwargs).reset_index()

  File "C:\Users\mydev\Miniconda3\envs\jlab3\lib\site-packages\pandas\core\groupby\generic.py", line 945, in aggregate
    result, how = aggregate(self, func, *args, **kwargs)

  File "C:\Users\mydev\Miniconda3\envs\jlab3\lib\site-packages\pandas\core\aggregation.py", line 577, in aggregate
    return getattr(obj, f)(), None

  File "C:\Users\mydev\Miniconda3\envs\jlab3\lib\site-packages\pandas\core\groupby\groupby.py", line 1496, in mean
    return self._cython_agg_general(

  File "C:\Users\mydev\Miniconda3\envs\jlab3\lib\site-packages\pandas\core\groupby\generic.py", line 1015, in _cython_agg_general
    agg_mgr = self._cython_agg_blocks(

  File "C:\Users\mydev\Miniconda3\envs\jlab3\lib\site-packages\pandas\core\groupby\generic.py", line 1114, in _cython_agg_blocks
    raise DataError("No numeric types to aggregate")

pandas.core.base.DataError: No numeric types to aggregate
```
</p></details>

## Version info
<details><summary>conda env</summary><p>

```
Windows 10
- hvplot            0.7.0   
- python           3.8.6   
- pandas           1.2.1   
- numpy            1.19.5  
- bokeh             2.2.3   
- holoviews       1.14.1
- pyviz_comms  2.0.1
```
</p></details>

**Comment by jlstevens** [comment] 2021-02-01 16:45
Thanks for reporting this, I've just confirmed the problem for myself. Assigning to the next milestone.

**Comment by philippjfr** [comment] 2021-02-01 18:34
I'd probably consider this a Pandas bug, but we'll have to work around this in hvPlot. The problem is that pd.melt does not keep the correct dtype for the new style Int64Type columns when performing a `pd.melt` operation, which means that `df.groupby(...).mean()` errors out with `No numeric types to aggregate`.

**Comment by CodeCox** [comment] 2021-02-02 10:54
It does seem to be a broader problem related to the new Pandas extension dtypes i.e. I get the same error for `Float64`.

Another instance of the 'aggregation' problem can be seen with `hvplot.hist()` - The traceback error is _`IntegerArray` object has no attribute 'values'._ Likewise with `FloatingArray`.

I guess this will be the case for all the Pandas Integer and Float dtype variations - and it will probably impact all plots that may 'group' these types.

**Comment by philippjfr** [comment] 2021-02-02 10:57
Right, it is a general problem. 

>Another instance of the 'aggregation' problem can be seen with hvplot.hist() - The traceback error is IntegerArray object has no attribute 'values'. Likewise with FloatingArray.

I've fixed this one in https://github.com/holoviz/holoviews/pull/4817. For the aggregation issue we'll have to fix all occurrences of `melt` operations in hvPlot.

**Comment by jbednar** [comment] 2021-02-02 15:53
Is this not something that should be fixed in Pandas instead?

**Comment by philippjfr** [comment] 2021-02-02 16:02
Sure, but I can guarantee that users will have broken versions of Pandas for years to come.

**Comment by philippjfr** [comment] 2021-05-21 23:01
Appears to be fixed in pandas now.

**Closed by philippjfr** 2021-05-21 23:01 UTC
Labels: type: bug
