### ISSUE TITLE
Add support for hover when datashade points

### ISSUE THREAD

**Issue by ahuang11** [holoviz/hvplot#1428] opened 2024-09-30 22:32 UTC
Through ship traffics, I realized I can add hover tooltips to datashaded/rasterized plots; either through `hd.inspect_points` or a lookup_hook.
https://examples.holoviz.org/gallery/ship_traffic/ship_traffic.html#selecting-specific-datapoints

Can we have a reasonable default for hvPlot when `hover=True`? Or even HoloViews?

```python
import pandas as pd
import hvplot.pandas
import panel as pn
import datashader as ds
import holoviews as hv
import holoviews.operation.datashader as hd

pop = pd.DataFrame(
    {
        "lon": [-86.75, -86.5, -86.25, -86.0],
        "lat": [33.75, 34.0, 34.25, 34.5],
        "population": [100, 200, 300, 400],
        "R": ["A", "B", "A", "B"],
    }
)

# lon_lat_to_easting_northing
pop["x"], pop["y"] = hv.util.transform.lon_lat_to_easting_northing(
    pop["lon"], pop["lat"]
)
tiles = hv.element.tiles.EsriStreet()

alpha_slider = pn.widgets.FloatSlider(name="Population", start=0, end=1, step=0.1)

highlighter = hd.inspect_points.instance(streams=[hv.streams.Tap])

points = pop.hvplot.points(
    "x",
    "y",
    datashade=True,
    aggregator=ds.count_cat("R"),
    dynspread=True,
    height=800,
    width=1000,
)
highlight = highlighter(points).opts(
    color="white", tools=["hover"], marker="square", size=10, fill_alpha=0
)
points * highlight
```
![image](https://github.com/user-attachments/assets/737651e8-9d4c-4877-8b3f-e295f1415196)

Currently, if you just do hover=True alongside datashade, it gives a useless RGB value
```python
points = pop.hvplot.points(
    "x",
    "y",
    datashade=True,
    aggregator=ds.count_cat("R"),
    dynspread=True,
    height=800,
    width=1000,
    hover=True
)
points
```
<img width="404" alt="image" src="https://github.com/user-attachments/assets/f4dbabdb-791c-4653-84ec-b3e611d1e613">

**Comment by jbednar** [comment] 2024-09-30 22:47
That's certainly where I am hoping [instant inspections](https://github.com/orgs/holoviz/projects/9) will end up, revealing as close to what we offer for non-datashaded Bokeh by default, but appropriately modified to take aggregation into account.

**Comment by philippjfr** [comment] 2024-10-03 15:08
I don't think we're at the point where we can realistically offer this by default bound to a `PointerXY` stream simply because it's too slow and the experience will be sub-optimal. With the index layer approach that Simon will start working on very soon it may be okay.

**Comment by philippjfr** [comment] 2024-10-03 15:13
Indeed this is a duplicate of https://github.com/holoviz/hvplot/issues/1211

**Closed** 2024-10-04 12:12 UTC
Labels: type: enhancement
